# -*- coding: utf-8 -*-
"""api_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spFXVS4uTL3J2UA4JsxG2YF0uBZnidhP
"""

"""
Fetch 50K CS papers with institution data from OpenAlex using PyAlex.
OpenAlex has arXiv IDs + author affiliations built-in — no separate lookup needed.
Output: cs_papers_with_institutions.json saved to Google Drive
"""

# ── 0. Install ────────────────────────────────────────────────────────────
!pip install pyalex tqdm -q

from pyalex import Works, config
from google.colab import drive
import json, time, os
from tqdm import tqdm

# ── Mount Drive ───────────────────────────────────────────────────────────
drive.mount('/content/drive')

# ── CONFIG ────────────────────────────────────────────────────────────────
PROJECT_DIR = "/content/drive/MyDrive/arxiv-rag-project"
os.makedirs(PROJECT_DIR, exist_ok=True)
OUTPUT_FILE = os.path.join(PROJECT_DIR, "cs_papers_50k_with_institutions_final1.json")

TARGET     = 50_000
PER_PAGE   = 200       # OpenAlex max per page
config.email = "your_email@example.com"   # ← polite pool = faster, fewer rate limits

# ── Region mapping ────────────────────────────────────────────────────────
REGION_MAP = {
    "US": "America", "CA": "America", "BR": "America", "MX": "America",
    "AR": "America", "CL": "America", "CO": "America",
    "GB": "Europe",  "DE": "Europe",  "FR": "Europe",  "IT": "Europe",
    "ES": "Europe",  "NL": "Europe",  "SE": "Europe",  "CH": "Europe",
    "PL": "Europe",  "RU": "Europe",  "PT": "Europe",  "BE": "Europe",
    "AT": "Europe",  "DK": "Europe",  "NO": "Europe",  "FI": "Europe",
    "GR": "Europe",  "CZ": "Europe",  "HU": "Europe",  "RO": "Europe",
    "CN": "Asia",    "IN": "Asia",    "JP": "Asia",    "KR": "Asia",
    "SG": "Asia",    "TW": "Asia",    "HK": "Asia",    "IL": "Asia",
    "IR": "Asia",    "PK": "Asia",    "SA": "Asia",    "TR": "Asia",
    "AU": "Oceania", "NZ": "Oceania",
    "ZA": "Africa",  "NG": "Africa",  "EG": "Africa",  "KE": "Africa",
    "ET": "Africa",  "GH": "Africa",  "TN": "Africa",  "MA": "Africa",
}

def reconstruct_abstract(inverted_index):
    """OpenAlex stores abstracts as {word: [positions]} — reconstruct to plain text."""
    if not inverted_index:
        return None
    positions = {}
    for word, pos_list in inverted_index.items():
        for pos in pos_list:
            positions[pos] = word
    return " ".join(positions[i] for i in sorted(positions))

def get_region(country_code):
    if not country_code:
        return "Unknown"
    return REGION_MAP.get(country_code.upper(), "Other")

# ── Extract fields from one OpenAlex work ─────────────────────────────────
def extract_paper(work):
    # Get primary institution from first author
    primary_institution = None
    primary_country     = None
    region              = "Unknown"

    authorships = work.get("authorships") or []
    for authorship in authorships:
        insts = authorship.get("institutions") or []
        if insts:
            inst = insts[0]
            primary_institution = inst.get("display_name")
            primary_country     = inst.get("country_code")
            region              = get_region(primary_country)
            break   # first author with an institution wins

    # Get arXiv ID if available
    arxiv_id = None
    for loc in (work.get("locations") or []):
        src = loc.get("source") or {}
        if "arxiv" in (src.get("host_organization_name") or "").lower():
            landing = loc.get("landing_page_url") or ""
            if "arxiv.org/abs/" in landing:
                arxiv_id = landing.split("arxiv.org/abs/")[-1]
                break
    # fallback: ids.arxiv
    if not arxiv_id:
        arxiv_id = (work.get("ids") or {}).get("arxiv")

    return {
        "id":                  work.get("id"),
        "arxiv_id":            arxiv_id,
        "title":               (work.get("title") or "").strip(),
        "abstract":            reconstruct_abstract(work.get("abstract_inverted_index")),
        "publication_year":    work.get("publication_year"),
        "categories":          [t.get("display_name") for t in (work.get("topics") or [])[:3]],
        "primary_institution": primary_institution,
        "primary_country":     primary_country,
        "region":              region,
        "cited_by_count":      work.get("cited_by_count", 0),
        "doi":                 work.get("doi"),
    }

# ── Fetch loop ────────────────────────────────────────────────────────────
def fetch_papers(target=50_000):
    papers   = []
    seen_ids = set()

    # Filter: CS papers on arXiv, with abstracts, 2015-2024
    query = (
        Works()
        .filter(
            concepts={"wikidata": "https://www.wikidata.org/wiki/Q21198"},  # Computer Science
            has_abstract=True,
            locations={"source": {"id": "https://openalex.org/S4306400194"}},  # arXiv
        )
        .select([
            "id", "title", "abstract_inverted_index", "publication_year",
            "authorships", "topics", "cited_by_count",
            "doi", "ids", "locations"
        ])
    )

    pbar = tqdm(total=target, desc="Fetching papers")

    for page in query.paginate(per_page=PER_PAGE, n_max=target):
        for work in page:
            wid = work.get("id")
            if wid in seen_ids:
                continue
            seen_ids.add(wid)

            paper = extract_paper(work)

            # Only keep papers where we got an institution
            if not paper["primary_institution"]:
                continue

            papers.append(paper)
            pbar.update(1)

            if len(papers) >= target:
                pbar.close()
                return papers

        time.sleep(0.1)   # be polite to OpenAlex API

    pbar.close()
    return papers

# ── Run ───────────────────────────────────────────────────────────────────
print(f"Starting fetch — target: {TARGET:,} papers with institutions...")
papers = fetch_papers(TARGET)

print(f"\nFetched: {len(papers):,} papers with institution data")

# ── Region breakdown ──────────────────────────────────────────────────────
from collections import Counter
regions = Counter(p["region"] for p in papers)
print("\nRegion distribution:")
for region, count in regions.most_common():
    print(f"  {region:<12} {count:>6,}  ({count/len(papers):.1%})")

# ── Save ──────────────────────────────────────────────────────────────────
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(papers, f, indent=2, ensure_ascii=False)

print(f"\nSaved → {OUTPUT_FILE}")
print("Done!")